apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
      #same as in postgres pod file
      #no need to add nodeport as it is internal service
  selector:
    name: postgres-pod
    app: demo-voting-app