apiVersion: v1
kind: Pod
metadata:
 name: worker-app-pod
 labels:
   name: worker-app-pod
   app: demo-voting-app
spec:
 containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
   #ports are not required as working pod .NET will not listen to any service